// created by fuzzyfox
def COLOR_MAP = [
	'SUCCESS': 'good',
	'FAILURE': 'danger',
]
pipeline {
    agent any
    tools {
        maven "maven3.9"
        jdk "JDK17"
    }

    environment {
        registryCredential = 'ecr:us-east-1:awscreds'
        imageName = "565393070765.dkr.ecr.us-east-1.amazonaws.com/project02-app-img"
        projectRegistry = "https://565393070765.dkr.ecr.us-east-1.amazonaws.com"
		cluster = "ambitious-horse-hga8ey"
		service = "project02-app-task-service"
    }
  stages {
        stage('Fetch code') {
            steps {
               git branch: 'docker', url: 'https://github.com/hkhcoder/vprofile-project.git'
            }
        }

        stage("Build"){
			steps{
				sh 'mvn install -DskipTests'
			}
			post {
				success{
					echo "Archining artifact"
					archiveArtifacts artifacts: '**/*.war'
				}
			}
		}

		stage("Unit test"){
			steps{
				sh 'mvn test'
			}
		}
		stage("CheckStyle analysis"){
			steps{
				sh 'mvn checkstyle:checkstyle'
			}
		}

		stage("Sonar code analysis"){
			environment {
				scannerHome = tool 'sonar6.2' // the name when you add in scanner
			}
			steps{
				withSonarQubeEnv('sonarserver'){
					sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                   -Dsonar.projectName=vprofile-repo \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
				}
			}
		}
		// setup: create quality gate -> create webhook for contact
		stage("Quality Gate"){
			steps{
				timeout(time:1, unit:'HOURS'){
					waitForQualityGate abortPipeline: true
				}
			}
		}

        stage('Build App Image') {
          steps {
       
            script {
                dockerImage = docker.build( imageName + ":$BUILD_NUMBER", "./Docker-files/app/multistage/")
                }
          }
    
        }

        stage('Upload App Image') {
          steps{
            script {
              docker.withRegistry( projectRegistry, registryCredential ) {
                dockerImage.push("$BUILD_NUMBER")
                dockerImage.push('latest')
              }
            }
          }
        }
	    // upload to ECR but still in Jenkins
        stage('Remove Container Images'){
            steps{
                sh 'docker rmi -f $(docker images -a -q)'
            }
        }
		// deploy to ECS
	  	stage('Deploy to ECS'){
			steps{
				withAWS(credentials: 'awscreds', region:'us-east-1'){
					// get latest img -> run container -> run task
					sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
				}
			}
		}
  }

    // notifications with Slack
	post {
		always {
			echo 'Slack notifications.'
			slackSend channel: '#all-it',
				color: COLOR_MAP[currentBuild.currentResult], // function above
				//message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} "
				message: """*${currentBuild.currentResult}:* Job *${env.JOB_NAME}* build *#${env.BUILD_NUMBER}*
<${env.BUILD_URL}|Open build in Jenkins>"""
		}
	}


}